// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC-dDyBCvJvVuL49mltqp3ONR6oxjBe2s',
    appId: '1:1026437829076:android:d4b8d2a68834d252af4641',
    messagingSenderId: '1026437829076',
    projectId: 'newsa-29b96',
    storageBucket: 'newsa-29b96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ2W8d_k4KORISxgPWbT770iMfcOhe3v0',
    appId: '1:1026437829076:ios:b96f4704ea264af0af4641',
    messagingSenderId: '1026437829076',
    projectId: 'newsa-29b96',
    storageBucket: 'newsa-29b96.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY41qJVLG_PlhHkO6UVCoDxa8dGXZMQ08',
    appId: '1:1026437829076:web:b9b04fcdd5387882af4641',
    messagingSenderId: '1026437829076',
    projectId: 'newsa-29b96',
    authDomain: 'newsa-29b96.firebaseapp.com',
    storageBucket: 'newsa-29b96.firebasestorage.app',
    measurementId: 'G-0YZ4G97ZQ4',
  );
}
